"""
Icons and the splash screen of CSU-RP1210.

The icons are original SVG artwork in icons/ (generated by tools/make_icons.py,
under this project's license). They are rendered with QtSvg at the sizes Qt asks
for, so they stay sharp on high-DPI screens and need no image plugins.
"""

import os
import sys

from PyQt5.QtCore import QByteArray, QRectF, Qt
from PyQt5.QtGui import QColor, QFont, QIcon, QImage, QPainter, QPixmap
from PyQt5.QtSvg import QSvgRenderer
from PyQt5.QtWidgets import QApplication, QSplashScreen

ICON_DIR = os.path.join(getattr(sys, "_MEIPASS", os.path.dirname(os.path.abspath(__file__))), "icons")
SIZES = (16, 20, 24, 32, 48, 64)
_icons = {}


def svg_path(name):
    return os.path.join(ICON_DIR, name + ".svg")


def image_path(name):
    """PNG of an icon, for rich-text labels (<img src=...>)."""
    return os.path.join(ICON_DIR, name + ".png").replace("\\", "/")


def render(name, width, height=None, scale=1.0):
    renderer = QSvgRenderer(svg_path(name))
    image = QImage(int(width * scale), int((height or width) * scale), QImage.Format_ARGB32_Premultiplied)
    image.fill(Qt.transparent)
    painter = QPainter(image)
    painter.setRenderHints(QPainter.Antialiasing | QPainter.TextAntialiasing | QPainter.SmoothPixmapTransform)
    renderer.render(painter)
    painter.end()
    image.setDevicePixelRatio(scale)
    return image


def icon(name):
    """QIcon of an icon at the usual sizes (empty icon if the file is missing)."""
    if name not in _icons:
        result = QIcon()
        if os.path.exists(svg_path(name)):
            for size in SIZES:
                result.addPixmap(QPixmap.fromImage(render(name, size)))
        _icons[name] = result
    return _icons[name]


class Splash(QSplashScreen):
    """Start-up screen: the artwork plus the version and a progress message."""

    def __init__(self, version=""):
        scale = QApplication.instance().devicePixelRatio() if QApplication.instance() else 1.0
        pixmap = QPixmap.fromImage(render("splash", 600, 340, scale))
        if version:
            painter = QPainter(pixmap)
            painter.setRenderHint(QPainter.TextAntialiasing)
            painter.setPen(QColor("#c8c372"))
            painter.setFont(QFont("Arial", 10))
            painter.drawText(QRectF(232, 214, 340, 24), Qt.AlignLeft | Qt.AlignVCenter, "Version " + version)
            painter.end()
        super(Splash, self).__init__(pixmap)

    def message(self, text):
        self.showMessage("  " + text, Qt.AlignBottom | Qt.AlignLeft, QColor("#ffffff"))
        QApplication.processEvents()


def show_splash(version=""):
    """Show the splash screen and close the executable's unpacking splash, if any."""
    splash = Splash(version)
    splash.show()
    splash.message("Starting...")
    try:
        import pyi_splash  # PyInstaller bootloader splash (shown while the exe unpacks)
        pyi_splash.close()
    except ImportError:
        pass
    return splash
